version: 2.1

orbs:
  python: circleci/python@2.1

commands:
  setup-env:
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          packages:
            - uv
      - run:
          name: Setup environment with uv
          command: |
            uv venv
            . .venv/bin/activate
            uv pip install ruff mypy pytest pytest-cov
            uv pip install -e mail_api
            uv pip install -e mail_gmail_impl
            uv pip install -e tests

jobs:
  lint:
    docker:
      - image: cimg/python:3.11
    steps:
      - setup-env
      - run:
          name: Run ruff linter
          command: |
            . .venv/bin/activate
            ruff check .
      - run:
          name: Run type checking with mypy
          command: |
            . .venv/bin/activate
            mypy mail_api/ mail_gmail_impl/ tests/

  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - setup-env
      - run:
          name: Run tests with coverage
          command: |
            . .venv/bin/activate
            mkdir -p test-results
            pytest tests/src/tests/__init__.py \
              --cov=mail_api \
              --cov=mail_gmail_impl \
              --junitxml=test-results/results.xml
            coverage report -m
            coverage html -d coverage-report
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: unit-test-results
      - store_artifacts:
          path: coverage-report
          destination: coverage-html

workflows:
  version: 2
  lint-and-test:
    jobs:
      - lint
      - test
