# yaml-language-server: $schema=https://circleci.com/schemas/1.0/config.json
version: 2.1

jobs:
  test:
    docker:
      - image: python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install uv
            uv pip install --system pytest mypy ruff coverage
      - run:
          name: Run static analysis
          command: ruff check . && mypy src/
      - run:
          name: Run tests
          command: coverage run -m pytest
      - run:
          name: Generate coverage report
          command: coverage report -m
      - store_test_results:
          path: test-results/

workflows:
  test_pipeline:
    jobs:
      - test
