version: 2.1

orbs:
  python: circleci/python@1.2

commands:
  setup-env:
    steps:
      - checkout
      - run:
          name: Setup Python and install dependencies
          command: |
            pip install uv
            uv venv
            . .venv/bin/activate
            uv pip install

jobs:
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - setup-env
      - run:
          name: Run static analysis (ruff & mypy)
          command: |
            . .venv/bin/activate
            ruff check .
            mypy mail_api/ mail_gmail_impl/
      - run:
          name: Run tests with coverage
          command: |
            . .venv/bin/activate
            mkdir -p test-results
            pytest tests/src/tests \
              --cov=mail_api --cov=mail_gmail_impl \
              --junitxml=test-results/results.xml
            coverage report -m
            coverage html -d coverage-report
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: unit-test-results
      - store_artifacts:
          path: coverage-report
          destination: coverage-html

workflows:
  test-all:
    fail_fast: true
    jobs:
      - test
