jobs:
  lint:
    docker:
      - image: cimg/python:3.11
    steps:
      - setup-env
      - run:
          name: Run ruff and mypy
          command: |
            uv run ruff check .
            uv run mypy mail_api mail_gmail_impl

  unit-test:
    docker:
      - image: cimg/python:3.11
    steps:
      - setup-env
      - run:
          name: Run pytest with coverage
          command: |
            mkdir -p test-results
            uv run pytest tests/src/tests \
              --cov=mail_api --cov=mail_gmail_impl \
              --junitxml=test-results/results.xml
            uv run coverage report -m
            uv run coverage html -d coverage-report
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: unit-test-results
      - store_artifacts:
          path: coverage-report
          destination: coverage-html

workflows:
  test-all:
    jobs:
      - lint
      - unit-test
